/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
    './src/**/**/*.{js,jsx,ts,tsx}',
    './src/**/**/**/*.{js,jsx,ts,tsx}',
    './src/**/**/**/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    screens: {
      'sm': '500px',
      // => @media (min-width: 640px) { ... }

      'md': '768px',
      // => @media (min-width: 768px) { ... }

      'lg': '1024px',
      // => @media (min-width: 1024px) { ... }

      'xl': '1512px',
      // => @media (min-width: 1280px) { ... }

      '2xl': '1920px',
      // => @media (min-width: 1536px) { ... }
    },
    colors: {
      'transparent': 'transparent',
      'blue-light': '#eef5f9',
      'blue-light-hover': '#e6f0f6',
      'blue-light-active': '#ccdfed',
      'blue-normal': '#5998c5',
      'blue-normal-hover': '#5089b1',
      'blue-normal-active': '#477a9e',
      'blue-dark': '#437294',
      'blue-dark-hover': '#355b76',
      'blue-dark-active': '#284459',
      'blue-darker': '#1f3545',
      'white-light': '#ffffff',
      'white-light-hover': '#ffffff',
      'white-light-active': '#fffffe',
      'white-normal': '#fffffc',
      'white-normal-hover': '#e6e6e3',
      'white-normal-active': '#ccccca',
      'white-dark': '#bfbfbd',
      'white-dark-hover': '#999997',
      'white-dark-active': '#737371',
      'white-darker': '#595958',
      'black-light': '#e6e6e6',
      'black-light-hover': '#d9d9d9',
      'black-light-active': '#b0b0b0',
      'black-normal': '#000000',
      'black-normal-hover': '#000000',
      'black-normal-active': '##000000',
      'black-dark': '#000000',
      'black-dark-hover': '#000000',
      'black-dark-active': '#000000',
      'black-darker': '#000000',
      'navigation': 'rgba(0, 0, 0, .85)',
      'hover': 'rgba(0, 0, 0, .5)',
    },
    fontFamily: {
      sans: ['Roboto', 'sans-serif'],
      serif: ['Lora', 'serif'],
      mono: ['Source Code Pro', 'monospace'],
    },
    fontSize: {
      'xs': '12px',
      'sm': '14px',
      'tiny': '12px',
      'base': '16px',
      'lg': '20px',
      'xl': '22px',
      '2xl': '24px',
      '3xl': '28px',
      '4xl': '32px',
      '5xl': '36px',
      '6xl': '45px',
      '7xl': '57px',
      'body-sm': '12px',
      'body-md': '14px',
      'body-lg': '17.5px',
      'heading-sm': '22px',
      'heading-md': '28px',
      'heading-lg': '34px',
    },
    fontWeight: {
      'hairline': 100,
      'extra-light': 100,
      'thin': 200,
      'light': 300,
      'normal': 400,
      'medium': 500,
      'semibold': 600,
      'bold': 700,
      'extrabold': 800,
      'extra-bold': 800,
      'black': 900,
    },
    borderRadius: {
      'none': '0',
      'sm': '2px',
      'DEFAULT': '4px',
      'md': '6px',
      'lg': '8px',
      'xl': '12px',
      '2xl': '16px',
      '3xl': '24px',
      'full': '9999px',
      'large': '12px',
    },
  },
  plugins: [],
};
